### ISSUE TITLE
Reader panics when trying to read a .xlsx

### ISSUE THREAD

**Issue by SpyrosRoum** [MathNya/umya-spreadsheet#1]
This is my code: 
```rust
use umya_spreadsheet::reader;

fn main() {
    let opt = Opt::from_args();
    let in_sheet = reader::xlsx::read(opt.input.as_path()).expect("Didn't find input");
}
```

And this is the panic:
```
thread 'main' panicked at 'attempt to subtract with overflow', /home/spyros/.cargo/registry/src/github.com-1ecc6299db9ec823/umya-spreadsheet-0.1.12-beta/src/structs/color.rs:123:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Any idea why this is happening? If you need more info or the StructOpt struct let me know

**Comment by MathNya** [comment]
Thank you for your report.

The cause of the problem has been found.
If you specify white as the text color, an error will occur.
We will fix the problem at the next update.

**Comment by SpyrosRoum** [comment]
Just to be clear, the code above is the exact code that would error (the struct for StructOpt is only missing), I did not specify anything and nothing is different than the first two lines of the example.

**Comment by MathNya** [comment]
Fixed a bug. Please try again after getting the latest source code.

**Comment by SpyrosRoum** [comment]
For the same code there is a different panic now 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Xml(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }))', /home/spyros/.cargo/registry/src/github.com-1ecc6299db9ec823/umya-spreadsheet-0.1.13-beta/src/reader/xlsx.rs:85:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This is with backtrace = 1:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Xml(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }))', /home/spyros/.cargo/registry/src/github.com-1ecc6299db9ec823/umya-spreadsheet-0.1.13-beta/src/reader/xlsx.rs:85:35
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1269
  14: core::result::Result<T,E>::unwrap
             at /home/spyros/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:1005
  15: umya_spreadsheet::reader::xlsx::read
             at /home/spyros/.cargo/registry/src/github.com-1ecc6299db9ec823/umya-spreadsheet-0.1.13-beta/src/reader/xlsx.rs:85
  16: support::main
             at src/main.rs:25
  17: std::rt::lang_start::{{closure}}
             at /home/spyros/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  20: std::panicking::try
             at src/libstd/panicking.rs:325
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  23: std::rt::lang_start
             at /home/spyros/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  24: main
  25: __libc_start_main
  26: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by MathNya** [comment]
There seems to be a problem with the theme loading process.
The next update will fix it to avoid the error.

**Comment by SpyrosRoum** [comment]
Thank, also I'm sorry for going off topic but I'm wondering if it's possible to insert a new row instead of writing to a pre-existing one.

**Comment by MathNya** [comment]
The ability to insert rows is not yet supported.
We are planning to support it as a high-priority function.

**Comment by MathNya** [comment]
Fixed a bug related to loading themes. Please get the latest source code and try again.

**Comment by SpyrosRoum** [comment]
It looks like it read it with no issues so I'm closing the issue. Thanks!
