### ISSUE TITLE
Panic when reading xlsx with formula.

### ISSUE THREAD

**Issue by yorkz1994** [MathNya/umya-spreadsheet#216]
When reading a xlsx file with formula, below panic happened.
```
thread 'main' panicked at \src\index.crates.io-6f17d22bba15001f\umya-spreadsheet-2.0.1\src\helper\formula.rs:797:46:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\std\src\panicking.rs:652
   1: core::panicking::panic_fmt
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\core\src\panicking.rs:72
   2: core::panicking::panic
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\core\src\panicking.rs:146
   3: core::option::unwrap_failed
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\core\src\option.rs:1985
   4: enum2$<core::option::Option<u32> >::unwrap
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9\library\core\src\option.rs:935
   5: umya_spreadsheet::helper::formula::adjustment_insert_formula_coordinate
             at \src\index.crates.io-6f17d22bba15001f\umya-spreadsheet-2.0.1\src\helper\formula.rs:797
   6: umya_spreadsheet::structs::cell_formula::CellFormula::set_attributes<std::io::cursor::Cursor<ref$<alloc::vec::Vec<u8,alloc::alloc::Global> > > >
             at \src\index.crates.io-6f17d22bba15001f\umya-spreadsheet-2.0.1\src\structs\cell_formula.rs:191    
   7: umya_spreadsheet::structs::cell::Cell::set_attributes<std::io::cursor::Cursor<ref$<alloc::vec::Vec<u8,alloc::alloc::Global> > > >      
             at \src\index.crates.io-6f17d22bba15001f\umya-spreadsheet-2.0.1\src\structs\cell.rs:326
   8: umya_spreadsheet::structs::row::Row::set_attributes<std::io::cursor::Cursor<ref$<alloc::vec::Vec<u8,alloc::alloc::Global> > > >        
             at \src\index.crates.io-6f17d22bba15001f\umya-spreadsheet-2.0.1\src\structs\row.rs:142
   9: umya_spreadsheet::reader::xlsx::worksheet::read
             at \src\index.crates.io-6f17d22bba15001f\umya-spreadsheet-2.0.1\src\reader\xlsx\worksheet.rs:70    
  10: umya_spreadsheet::reader::xlsx::raw_to_deserialize_by_worksheet
             at \src\index.crates.io-6f17d22bba15001f\umya-spreadsheet-2.0.1\src\reader\xlsx.rs:128
  11: umya_spreadsheet::structs::spreadsheet::Spreadsheet::read_sheet_collection
             at \src\index.crates.io-6f17d22bba15001f\umya-spreadsheet-2.0.1\src\structs\spreadsheet.rs:323     
  12: umya_spreadsheet::reader::xlsx::read_reader<std::fs::File>
             at \src\index.crates.io-6f17d22bba15001f\umya-spreadsheet-2.0.1\src\reader\xlsx.rs:79
  13: umya_spreadsheet::reader::xlsx::read<ref$<str$> >
             at \src\index.crates.io-6f17d22bba15001f\umya-spreadsheet-2.0.1\src\reader\xlsx.rs:97
  14: excel::main
             at .\src\main.rs:4
  15: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9\library\core\src\ops\function.rs:250
  16: core::hint::black_box
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9\library\core\src\hint.rs:338
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `D:\tmp\target\debug\excel.exe` (exit code: 101)
```

I did some debug, it seems formula token parser has problem?
e.g.
```#[test]
    fn test_it() {
        let formula = "=10+9";
        let tokens = parse_to_tokens(formula);
        dbg!(tokens);
    }
```
Output:
```
[src\helper\formula.rs:903:9] tokens = [        
    FormulaToken {
        value: StringValue {
            value: Some(
                "10+9",
            ),
        },
        token_type: Operand,
        token_sub_type: Range,
    },
]```

Is this parse correct?

**Comment by MathNya** [comment]
@yorkz1994 
Thank you for your report.
We will investigate the cause.

**Comment by harmbuisman** [comment]
I have the same problem. Reproducible with:
`umya_spreadsheet::reader::xlsx::read("base_template_cleared.xlsx");`

gives:
```
.cargo\registry\src\index.crates.io-6f17d22bba15001f\umya-spreadsheet-2.0.1\src\helper\formula.rs:797:46:
called `Option::unwrap()` on a `None` value
```

umya-spreadsheet = "2.0.1"

Example that gives the issue:
[base_template_cleared.xlsx](https://github.com/user-attachments/files/16560056/base_template_cleared.xlsx)

**Comment by MathNya** [comment]
Fixed issue.
Please get the latest version and check it.

**Comment by yorkz1994** [comment]
Thanks for the fix.
It works now.
