### ISSUE TITLE
Can't read a .xlsx file that exported by Google Spreadsheets

### ISSUE THREAD

**Issue by usagi** [MathNya/umya-spreadsheet#64]
## Repro

1. Create a new Google Spreadsheets document.
2. File -> Download -> Microsoft Excel (.xlsx)
3. Use `umya_spreadsheet::reader::xlsx::read_reader`/`read` to the file.

## Error log

```
panicked at 'called `Result::unwrap()` on an `Err` value: Zip(FileNotFound)', C:\Users\usagi\.cargo\registry\src\github.com-1ecc6299db9ec823\umya-spreadsheet-0.6.0\src\reader\xlsx.rs:76:46
stack backtrace:
(...brabrabra...)
```

- https://github.com/MathNya/umya-spreadsheet/blob/0.7.0/src/reader/xlsx.rs#L76

## Note

- Once this file is opened in Microsoft Excel and saved over, it no longer causes problems.

**Comment by usagi** [comment]
8f9d487 worked with Google exported files but it panicked one case. The file of the test case has a merged cell with border settings, maybe it related to #67 fixing.

![image](https://user-images.githubusercontent.com/115972/163810462-c013e878-83fa-407f-9f48-7b5c9654d09f.png)

```
thread 'test' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\usagi\.cargo\git\checkouts\umya-spreadsheet-795c6f88794c94f0\8f9d487\src\structs\stylesheet.rs:205:53
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/efec545293b9263be9edfb283a7aa66350b3acbf\/library\std\src\panicking.rs:498
   1: core::panicking::panic_fmt
             at /rustc/efec545293b9263be9edfb283a7aa66350b3acbf\/library\core\src\panicking.rs:107
   2: core::panicking::panic
             at /rustc/efec545293b9263be9edfb283a7aa66350b3acbf\/library\core\src\panicking.rs:48
   3: enum$<core::option::Option<ref$<umya_spreadsheet::structs::font::Font> >, 1, 18446744073709551615, Some>::unwrap<ref$<umya_spreadsheet::structs::font::Font> >
             at /rustc/efec545293b9263be9edfb283a7aa66350b3acbf\library\core\src\option.rs:747
   4: umya_spreadsheet::structs::stylesheet::Stylesheet::get_style_by_cell_format
             at C:\Users\usagi\.cargo\git\checkouts\umya-spreadsheet-795c6f88794c94f0\8f9d487\src\structs\stylesheet.rs:205
   5: umya_spreadsheet::structs::stylesheet::Stylesheet::make_style
             at C:\Users\usagi\.cargo\git\checkouts\umya-spreadsheet-795c6f88794c94f0\8f9d487\src\structs\stylesheet.rs:164
   6: umya_spreadsheet::reader::xlsx::styles::read<std::fs::File>
             at C:\Users\usagi\.cargo\git\checkouts\umya-spreadsheet-795c6f88794c94f0\8f9d487\src\reader\xlsx\styles.rs:74
   7: umya_spreadsheet::reader::xlsx::read_reader<std::fs::File>
             at C:\Users\usagi\.cargo\git\checkouts\umya-spreadsheet-795c6f88794c94f0\8f9d487\src\reader\xlsx.rs:94
   8: umya_spreadsheet::reader::xlsx::read
             at C:\Users\usagi\.cargo\git\checkouts\umya-spreadsheet-795c6f88794c94f0\8f9d487\src\reader\xlsx.rs:126
   9: test
             at C:\Users\usagi\tmp\test\src\main.rs:50
brabra..
```

Thank you for the challenge. 👍

**Comment by MathNya** [comment]
We have resolved the event you indicated.
Please check after obtaining the latest version.

**Comment by usagi** [comment]
I did a quick check on v0.7.1 to make sure it works. It is resolved. Thanks! 🎊
